
 try
 {
    console.log(a); 
    

 }
//  console.log("hi bye");
 catch
 {

 console.log("we got an error");
 }
